"""Add why and actions to alerts

Revision ID: 4383ef61633f
Revises: ba7d61cb5401
Create Date: 2026-08-28 21:11:35.044793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4383ef61633f'
down_revision = 'ba7d61cb5401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('why', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('actions', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('actions')
        batch_op.drop_column('why')

    # ### end Alembic commands ###
