"""Initial schema

Revision ID: ba7d61cb5401
Revises: 
Create Date: 2026-07-13 09:19:14.462620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7d61cb5401'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Make username column nullable so upgrade succeeds
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')
    # ### end Alembic commands ###
