"""Add notification fields to Alert

Revision ID: d4109d61b0e6
Revises: f859ad821c78
Create Date: 2026-06-17 07:58:27.818886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4109d61b0e6'
down_revision = 'f859ad821c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notification_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('notification_type')
        batch_op.drop_column('notified_at')

    # ### end Alembic commands ###
