"""Add acknowledge + audit trail fields to Alert

Revision ID: f859ad821c78
Revises: d60975c85041
Create Date: 2026-06-16 14:38:47.832437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f859ad821c78'
down_revision = 'd60975c85041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acknowledged', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('resolved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('acknowledged_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('acknowledged_at')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('acknowledged')

    # ### end Alembic commands ###
